import { ArrowRight, X } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { businessApi } from "../../api/businessApi";

export function GallerySection() {
  const [selected, setSelected] = useState<string | null>(null);
  const { data: images = [], isLoading, isError } = useQuery({ queryKey: ["gallery"], queryFn: businessApi.getGallery });
  return <section id="gallery" className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><div className="max-w-md"><p className="flex items-center gap-2 text-[11px] font-extrabold tracking-[.18em] text-[#9a7100]"><span className="h-px w-7 bg-[#FFC928]" /> TRAVEL EXPERIENCE</p><h2 className="mt-4 text-4xl font-extrabold leading-tight tracking-tight text-[#171717] sm:text-5xl">Made for the moments you remember.</h2><p className="mt-5 text-sm leading-7 text-[#666] sm:text-base">A look at the journeys we are proud to make comfortable, safe and memorable.</p></div>{isLoading ? <p className="mt-10 text-sm text-[#64748B]">Loading gallery...</p> : isError ? <p className="mt-10 text-sm text-[#B42318]">Gallery is unavailable right now.</p> : images.length === 0 ? <p className="mt-10 text-sm text-[#64748B]">Our journey gallery will be available shortly.</p> : <div className="mt-10 columns-1 gap-4 sm:columns-2 lg:columns-3">{images.map((image) => <button type="button" key={image._id} onClick={() => setSelected(image.url)} className="group relative mb-4 block w-full overflow-hidden rounded-lg bg-[#f7f7f7] text-left"><img src={image.url} alt={image.alt} className="w-full transition duration-500 group-hover:scale-105" /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-4 pb-3 pt-10 text-xs font-bold text-white opacity-0 transition group-hover:opacity-100">{image.alt}</span></button>)}</div>}<a href="#book" className="mt-8 inline-flex items-center rounded-lg bg-[#171717] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#FFC928] hover:text-[#171717]">Plan your next trip <ArrowRight className="ml-2" size={16} /></a></div>{selected && <div className="fixed inset-0 z-[80] grid place-items-center bg-[#071D49]/90 p-5" role="dialog" aria-modal="true"><button onClick={() => setSelected(null)} className="absolute right-5 top-5 text-white" aria-label="Close image preview"><X /></button><img src={selected} alt="Gallery preview" className="max-h-[88vh] max-w-full rounded-lg object-contain" /></div>}</section>;
}
